// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxdkublyvozvwaolwusy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZGt1Ymx5dm96dndhb2x3dXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NjQ2MzgsImV4cCI6MjA1MjE0MDYzOH0.rDeigDJFugyT7xMkIaB6IMUiN3bxSHY4jkMJAHhWt7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);